/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as VttRouteImport } from "./routes/vtt";
import { Route as TypesRouteImport } from "./routes/types";
import { Route as SettingsRouteImport } from "./routes/settings";
import { Route as NetworkRouteImport } from "./routes/network";
import { Route as GroupsRouteImport } from "./routes/groups";
import { Route as ChatRouteImport } from "./routes/chat";
import { Route as CharactersRouteImport } from "./routes/characters";
import { Route as IndexRouteImport } from "./routes/index";

const VttRoute = VttRouteImport.update({
  id: "/vtt",
  path: "/vtt",
  getParentRoute: () => rootRouteImport,
} as any);
const TypesRoute = TypesRouteImport.update({
  id: "/types",
  path: "/types",
  getParentRoute: () => rootRouteImport,
} as any);
const SettingsRoute = SettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => rootRouteImport,
} as any);
const NetworkRoute = NetworkRouteImport.update({
  id: "/network",
  path: "/network",
  getParentRoute: () => rootRouteImport,
} as any);
const GroupsRoute = GroupsRouteImport.update({
  id: "/groups",
  path: "/groups",
  getParentRoute: () => rootRouteImport,
} as any);
const ChatRoute = ChatRouteImport.update({
  id: "/chat",
  path: "/chat",
  getParentRoute: () => rootRouteImport,
} as any);
const CharactersRoute = CharactersRouteImport.update({
  id: "/characters",
  path: "/characters",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/characters": typeof CharactersRoute;
  "/chat": typeof ChatRoute;
  "/groups": typeof GroupsRoute;
  "/network": typeof NetworkRoute;
  "/settings": typeof SettingsRoute;
  "/types": typeof TypesRoute;
  "/vtt": typeof VttRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/characters": typeof CharactersRoute;
  "/chat": typeof ChatRoute;
  "/groups": typeof GroupsRoute;
  "/network": typeof NetworkRoute;
  "/settings": typeof SettingsRoute;
  "/types": typeof TypesRoute;
  "/vtt": typeof VttRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/characters": typeof CharactersRoute;
  "/chat": typeof ChatRoute;
  "/groups": typeof GroupsRoute;
  "/network": typeof NetworkRoute;
  "/settings": typeof SettingsRoute;
  "/types": typeof TypesRoute;
  "/vtt": typeof VttRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/characters"
    | "/chat"
    | "/groups"
    | "/network"
    | "/settings"
    | "/types"
    | "/vtt";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/characters"
    | "/chat"
    | "/groups"
    | "/network"
    | "/settings"
    | "/types"
    | "/vtt";
  id:
    | "__root__"
    | "/"
    | "/characters"
    | "/chat"
    | "/groups"
    | "/network"
    | "/settings"
    | "/types"
    | "/vtt";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  CharactersRoute: typeof CharactersRoute;
  ChatRoute: typeof ChatRoute;
  GroupsRoute: typeof GroupsRoute;
  NetworkRoute: typeof NetworkRoute;
  SettingsRoute: typeof SettingsRoute;
  TypesRoute: typeof TypesRoute;
  VttRoute: typeof VttRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/vtt": {
      id: "/vtt";
      path: "/vtt";
      fullPath: "/vtt";
      preLoaderRoute: typeof VttRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/types": {
      id: "/types";
      path: "/types";
      fullPath: "/types";
      preLoaderRoute: typeof TypesRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/settings": {
      id: "/settings";
      path: "/settings";
      fullPath: "/settings";
      preLoaderRoute: typeof SettingsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/network": {
      id: "/network";
      path: "/network";
      fullPath: "/network";
      preLoaderRoute: typeof NetworkRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/groups": {
      id: "/groups";
      path: "/groups";
      fullPath: "/groups";
      preLoaderRoute: typeof GroupsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/chat": {
      id: "/chat";
      path: "/chat";
      fullPath: "/chat";
      preLoaderRoute: typeof ChatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/characters": {
      id: "/characters";
      path: "/characters";
      fullPath: "/characters";
      preLoaderRoute: typeof CharactersRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CharactersRoute: CharactersRoute,
  ChatRoute: ChatRoute,
  GroupsRoute: GroupsRoute,
  NetworkRoute: NetworkRoute,
  SettingsRoute: SettingsRoute,
  TypesRoute: TypesRoute,
  VttRoute: VttRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
