create table public.relationship_versions (
	id bigint generated by default as identity primary key,
	relationship_id uuid not null references public."Relationships" (id) on delete cascade,
	from_id uuid not null,
	to_id uuid not null,
	relationship_type_id uuid not null,
	type_label text not null,
	description text not null,
	value_override double precision,
	effective_value double precision not null,
	change_kind text not null check (change_kind in ('baseline', 'created', 'updated')),
	changed_at timestamp with time zone not null default timezone('utc', now()),
	changed_by uuid references auth.users (id) on delete set null
);

create table public.relationship_version_reads (
	user_id uuid not null references auth.users (id) on delete cascade,
	relationship_id uuid not null references public."Relationships" (id) on delete cascade,
	last_read_version_id bigint not null references public.relationship_versions (id) on delete cascade,
	primary key (user_id, relationship_id)
);

create index relationship_versions_relationship_id_id_idx
	on public.relationship_versions (relationship_id, id desc);
create index relationship_versions_from_id_id_idx
	on public.relationship_versions (from_id, id desc);

alter table public.relationship_versions enable row level security;
alter table public.relationship_version_reads enable row level security;

revoke all on public.relationship_versions from anon, authenticated;
revoke all on public.relationship_version_reads from anon, authenticated;
grant select on public.relationship_versions to authenticated;
grant select, insert, update on public.relationship_version_reads to authenticated;

create policy "Authenticated users can read relationship versions"
	on public.relationship_versions
	for select
	to authenticated
	using (true);

create policy "Users can read their relationship version cursors"
	on public.relationship_version_reads
	for select
	to authenticated
	using (user_id = (select auth.uid()));

create policy "Users can create their relationship version cursors"
	on public.relationship_version_reads
	for insert
	to authenticated
	with check (user_id = (select auth.uid()));

create policy "Users can update their relationship version cursors"
	on public.relationship_version_reads
	for update
	to authenticated
	using (user_id = (select auth.uid()))
	with check (user_id = (select auth.uid()));

create or replace function public.set_relationship_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
	new.updated_at = timezone('utc', now());
	return new;
end;
$$;

create or replace function public.capture_relationship_version()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
	relationship_type public."RelationshipTypes"%rowtype;
begin
	select *
	into relationship_type
	from public."RelationshipTypes"
	where id = new."typeId";

	insert into public.relationship_versions (
		relationship_id,
		from_id,
		to_id,
		relationship_type_id,
		type_label,
		description,
		value_override,
		effective_value,
		change_kind,
		changed_at,
		changed_by
	)
	values (
		new.id,
		new."fromId",
		new."toId",
		new."typeId",
		coalesce(relationship_type.label, 'Unknown'),
		new.description,
		new.value,
		coalesce(new.value, relationship_type.value, 0),
		case when tg_op = 'INSERT' then 'created' else 'updated' end,
		case
			when tg_op = 'INSERT' then coalesce(new.created_at, timezone('utc', now()))
			else coalesce(new.updated_at, timezone('utc', now()))
		end,
		auth.uid()
	);

	return new;
end;
$$;

insert into public.relationship_versions (
	relationship_id,
	from_id,
	to_id,
	relationship_type_id,
	type_label,
	description,
	value_override,
	effective_value,
	change_kind,
	changed_at,
	changed_by
)
select
	relationship.id,
	relationship."fromId",
	relationship."toId",
	relationship."typeId",
	coalesce(relationship_type.label, 'Unknown'),
	relationship.description,
	relationship.value,
	coalesce(relationship.value, relationship_type.value, 0),
	'baseline',
	timezone('utc', now()),
	null
from public."Relationships" as relationship
left join public."RelationshipTypes" as relationship_type
	on relationship_type.id = relationship."typeId";

drop trigger if exists set_relationship_updated_at on public."Relationships";
create trigger set_relationship_updated_at
	before update on public."Relationships"
	for each row
	execute function public.set_relationship_updated_at();

create trigger capture_relationship_created
	after insert on public."Relationships"
	for each row
	execute function public.capture_relationship_version();

create trigger capture_relationship_updated
	after update of "description", "value", "typeId", "fromId", "toId"
	on public."Relationships"
	for each row
	when (
		old."description" is distinct from new."description"
		or old."value" is distinct from new."value"
		or old."typeId" is distinct from new."typeId"
		or old."fromId" is distinct from new."fromId"
		or old."toId" is distinct from new."toId"
	)
	execute function public.capture_relationship_version();

create or replace function public.get_unread_relationship_versions()
returns table (
	relationship_id uuid,
	from_id uuid,
	latest_version_id bigint,
	unread_count bigint
)
language sql
stable
security invoker
set search_path = ''
as $$
	select
		version.relationship_id,
		version.from_id,
		max(version.id) as latest_version_id,
		count(*) as unread_count
	from public.relationship_versions as version
	left join public.relationship_version_reads as reads
		on reads.relationship_id = version.relationship_id
		and reads.user_id = (select auth.uid())
	where (select auth.uid()) is not null
		and version.change_kind <> 'baseline'
		and version.changed_by is distinct from (select auth.uid())
		and version.id > coalesce(reads.last_read_version_id, 0)
	group by version.relationship_id, version.from_id;
$$;

create or replace function public.mark_relationship_versions_read(
	p_relationship_id uuid,
	p_last_read_version_id bigint
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
	current_user_id uuid := auth.uid();
begin
	if current_user_id is null then
		raise exception 'Authentication required';
	end if;

	if not exists (
		select 1
		from public.relationship_versions
		where relationship_id = p_relationship_id
			and id = p_last_read_version_id
	) then
		raise exception 'Invalid relationship version';
	end if;

	insert into public.relationship_version_reads (
		user_id,
		relationship_id,
		last_read_version_id
	)
	values (
		current_user_id,
		p_relationship_id,
		p_last_read_version_id
	)
	on conflict (user_id, relationship_id)
	do update set last_read_version_id = greatest(
		public.relationship_version_reads.last_read_version_id,
		excluded.last_read_version_id
	);
end;
$$;

revoke all on function public.set_relationship_updated_at() from public;
revoke all on function public.capture_relationship_version() from public;
revoke all on function public.get_unread_relationship_versions() from public, anon;
revoke all on function public.mark_relationship_versions_read(uuid, bigint) from public, anon;
grant execute on function public.get_unread_relationship_versions() to authenticated;
grant execute on function public.mark_relationship_versions_read(uuid, bigint) to authenticated;
